snap:amd64:
  image:
    name: ubuntudesktop/gnome-3-38-2004
  stage: deploy
  script:
  - export VERSION_NUMBER=`date +%y.%m.%d.%H%M`
  - snapcraft
  - echo ${SNAPCRAFT_LOGIN_FILE} | base64 --decode --ignore-garbage > snapcraft.login
  - snapcraft login --with snapcraft.login
  - snapcraft upload *.snap --release beta
  artifacts:
    paths:
    - subtitld*.snap
    expire_in: 1 week
  only:
  - master

snap-edge:amd64:
  image:
    name: ubuntudesktop/gnome-3-38-2004
  stage: deploy
  script:
  - export VERSION_NUMBER=`date +%y.%m.%d.%H%M`
  - snapcraft
  - echo ${SNAPCRAFT_LOGIN_FILE} | base64 --decode --ignore-garbage > snapcraft.login
  - snapcraft login --with snapcraft.login
  - snapcraft upload *.snap --release edge
  artifacts:
    paths:
    - subtitld*.snap
    expire_in: 1 week
  only:
  - master

appimage:amd64:
  image:
    name: ubuntu:focal
  stage: deploy
  before_script:
    - export VERSION_NUMBER=`date +%y.%m.%d.%H%M`
    - export DEBIAN_FRONTEND=noninteractive
    - apt update -qy
    - apt install -y wget git sshpass python3-pip libmpv-dev ffmpeg python3-setuptools patchelf desktop-file-utils libgdk-pixbuf2.0-dev fakeroot strace fuse libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-render-util0 libxcb-xinerama0 libxcb-xkb1 libxkbcommon-x11-0 libdrm2 libavresample4
    - python3 -m pip install --upgrade pip
    - wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage -O /usr/local/bin/appimagetool
    - chmod +x /usr/local/bin/appimagetool
    - python3 -m pip install -r requirements.txt
    - python3 -m pip install pyinstaller appimage-builder
    - mkdir AppDir
    - mkdir -p AppDir/usr/local/share/icons
    - cp subtitld/graphics/subtitld.png AppDir/usr/local/share/icons.
  script:
    - pyinstaller subtitld_linux.spec
    - mv dist/subtitld AppDir/subtitld
    - appimage-builder --skip-test
    - export SSHPASS=$USER_PASS
    - sshpass -e scp -o stricthostkeychecking=no *.AppImage jonata@jonata.org:/home/jonata/subtitld.jonata.org/appimage/
  artifacts:
    paths:
      - '*.AppImage'
    expire_in: 1 week
  only:
  - master

windows-nsis:
  image: schnouki/pyinstaller-windows-ci:python3
  stage: deploy
  script:
  - apt-get update -qy
  - apt-get install -y nsis openssh-client sshpass unzip
  - wget https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.zip --no-check-certificate
  - unzip ffmpeg-release-essentials.zip
  - wine pip3 install -U pip
  - wine pip3 install -r requirements.txt
  - wine pip3 install https://github.com/pyinstaller/pyinstaller/tarball/develop
  - wine pip3 install glfw
  - wine pyinstaller subtitld_win.spec
  - makensis subtitld_win.nsi
  - export SSHPASS=$USER_PASS
  - sshpass -e scp -o stricthostkeychecking=no Subtitld*Installer.exe jonata@jonata.org:/home/jonata/subtitld.jonata.org/packages/
  artifacts:
    paths:
    - Subtitld*Installer.exe
    expire_in: 1 week
  only:
  - master
