staging:amd64:
  image:
    name: ubuntu:18.04
  type: deploy
  script:
  - apt-get update -qy
  - apt-get install -y software-properties-common wget unzip
  #- add-apt-repository -y ppa:mc3man/mpv-tests
  #- add-apt-repository ppa:savoury1/graphics
  #- add-apt-repository ppa:savoury1/multimedia
  #- add-apt-repository ppa:savoury1/ffmpeg4
  #- cp /etc/apt/sources.list /etc/apt/sources.list~
  #- sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list
  #- apt-get update -qy
  - apt-get install -y python3-pip libglu1-mesa snapcraft git python devscripts equivs pkg-config freetype
  - git clone https://github.com/mpv-player/mpv-build.git
  - cd mpv-build
  - ./update
  - ./rebuild -j4
  - ./install
  - cd ..
  #libluajit-5.1-dev libass-dev libbluray-dev libuchardet-dev librubberband-dev libarchive-dev libavcodec-dev
  #- apt-get build-dep -y mpv libmpv1
  #- wget https://github.com/mpv-player/mpv/archive/v0.32.0.zip
  #- unzip v0.32.0.zip
  #- cd mpv-0.32.0
  #- ./bootstrap.py
  #- python3 ./waf configure
  #- python3 ./waf
  #- python3 ./waf install
  #- cd ..
  - python3 -m pip install --upgrade pip
  - python3 -m pip install -r requirements.txt
  - python3 -m pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
  - python3 -m PyInstaller subtitld_linux.spec
  - mv dist .dist
  - mv snap .snap
  - mv snapcraft.yaml .snapcraft.yaml
  - mv * /tmp/
  - mv .dist dist
  - mv .snap snap
  - mv .snapcraft.yaml snapcraft.yaml
  - snapcraft
  - echo $SNAPCRAFT_LOGIN_FILE | base64 --decode --ignore-garbage > snapcraft.login
  - snapcraft login --with snapcraft.login
  - snapcraft push *.snap --release beta
  artifacts:
    paths:
    - dist
    expire_in: 1 week
  only:
  - master

windows-nsis:
  image: schnouki/pyinstaller-windows-ci:python3
  type: deploy
  script:
  - apt-get update -qy
  - apt-get install -y nsis unzip openssh-client sshpass p7zip-full
  - wine pip3 install -r requirements.txt
  - wget https://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-latest-win64-static.zip
  - unzip ffmpeg-latest-win64-static.zip
  - wget https://mpv.srsfckn.biz/mpv-dev-latest.7z
  - 7z x -ompv mpv-dev-latest.7z
  - wine pyinstaller subtitld_win.spec
  - makensis subtitld_win.nsi
  - export SSHPASS=$USER_PASS
  - sshpass -e scp -o stricthostkeychecking=no Subtitld*Installer.exe jonata@jonata.org:/home/jonata/subtitld.jonata.org/packages/
  artifacts:
    paths:
    - Subtitld*Installer.exe
    expire_in: 1 week
  only:
  - master
