# snap:amd64:
#   image:
#     name: ubuntudesktop/gnome-3-38-2004
#   stage: deploy
#   script:
#   - export VERSION_NUMBER=`date +%y.%m.%d.%H%M`
#   - snapcraft
#   - echo ${SNAPCRAFT_LOGIN_FILE} | base64 --decode --ignore-garbage > snapcraft.login
#   - snapcraft login --with snapcraft.login
#   - snapcraft upload *.snap --release beta
#   artifacts:
#     paths:
#     - subtitld*.snap
#     expire_in: 1 week
#   only:
#   - master

snap-edge:amd64:
  image:
    name: ubuntudesktop/gnome-3-38-2004
  stage: deploy
  script:
  - export VERSION_NUMBER=`date +%y.%m.%d.%H%M`
  - snapcraft
  - echo ${SNAPCRAFT_LOGIN_FILE} | base64 --decode --ignore-garbage > snapcraft.login
  - snapcraft login --with snapcraft.login
  - snapcraft upload *.snap --release edge
  artifacts:
    paths:
    - subtitld*.snap
    expire_in: 1 week
  only:
  - master

appimage:amd64:
  image:
    name: appimagecrafters/appimage-builder
  stage: deploy
  before_script:
    # update appimage-builder (optional)
    - apt-get update
    - apt-get install -y git wget
    - pip3 install appimage-builder
    - pwd
    - mkdir -p AppDir/usr/share/icons/
    - cp subtitld/graphics/subtitld.png AppDir/usr/share/icons/.
  script:
    - appimage-builder --skip-test --recipe AppImageBuilder.yml
  artifacts:
    paths:
      - '*.AppImage'
    expire_in: 1 week
  only:
  - master

windows-nsis:
  image: schnouki/pyinstaller-windows-ci:python3
  stage: deploy
  script:
  - apt-get update -qy
  # - apt-get remove -y winbind
  - apt-get install -y nsis openssh-client sshpass unzip winbind
  - wget https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.zip --no-check-certificate
  - unzip ffmpeg-release-essentials.zip
  - wine "c:\Python37\python.exe" -m pip install -U pip
  - wine pip3 install -r requirements.txt
  - wine pip3 install https://github.com/pyinstaller/pyinstaller/tarball/develop
  - wine pip3 install glfw pywin32
  - wine pyinstaller subtitld_win.spec
  - makensis subtitld_win.nsi
  - export SSHPASS=$USER_PASS
  - sshpass -e scp -o stricthostkeychecking=no Subtitld*Installer.exe jonata@jonata.org:/home/jonata/subtitld.jonata.org/packages/
  artifacts:
    paths:
    - Subtitld*Installer.exe
    expire_in: 1 week
  only:
  - master
