snap-amd64:
  image:
    name: ubuntu:18.04
  type: deploy
  script:
  - export VERSION_NUMBER=`date +%y.%m.%d.%H%M`
  - apt-get update -qy
  - apt-get install -y software-properties-common wget
  - add-apt-repository ppa:mc3man/bionic-media -y
  - apt-get update -qy
  - apt-get install -y python3-pip libglu1-mesa snapcraft libmpv1 ffmpeg libmpv-dev libespeak-dev
  - python3 -m pip install --upgrade pip
  - python3 -m pip install -r requirements.txt
  - python3 -m pip uninstall -y enum34
  - python3 -m pip install pyinstaller==3.6
  - python3 -m PyInstaller subtitld_linux.spec
  - mv dist .dist
  - mv snap .snap
  - mv snapcraft.yaml .snapcraft.yaml
  - mv AppImageBuilder.yml .AppImageBuilder.yml
  - mv * /tmp/
  - mv .dist dist
  - mv .snap snap
  - mv .snapcraft.yaml snapcraft.yaml
  - snapcraft
  - echo $SNAPCRAFT_LOGIN_FILE | base64 --decode --ignore-garbage > snapcraft.login
  - snapcraft login --with snapcraft.login
  - snapcraft push *.snap --release beta
  artifacts:
    paths:
    - '*.snap'
    expire_in: 1 week
  only:
  - master

appimage-amd64:
  image: appimagecrafters/appimage-builder
  type: deploy
  before_script:
    - apt-get update -qy
    - apt-get install -y software-properties-common sshpass
    - add-apt-repository ppa:mc3man/bionic-media -y
    - apt-get update -qy
    - apt-get install -y git wget python3-pip libglu1-mesa libmpv1 ffmpeg libmpv-dev libespeak-dev
    - pip3 install --upgrade git+https://www.opencode.net/azubieta/appimagecraft.git
    - export VERSION_NUMBER=`date +%y.%m.%d.%H%M`
    - python3 -m pip install --upgrade pip
    - python3 -m pip install -r requirements.txt
    - python3 -m pip uninstall -y enum34
    - python3 -m pip install pyinstaller==3.6
  script:
    - python3 -m PyInstaller subtitld_linux.spec
    - mv dist/subtitld AppDir
    - mkdir -p /usr/share/icons/hicolor/512x512/
    - cp AppDir/graphics/subtitld.png /usr/share/icons/hicolor/512x512/.
    - appimage-builder --skip-test
    - export SSHPASS=$USER_PASS
    - sshpass -e scp -o stricthostkeychecking=no *.AppImage* jonata@jonata.org:/home/jonata/subtitld.jonata.org/appimage/
  artifacts:
    paths:
      - '*.AppImage*'
    expire_in: 1 week
  only:
  - master

windows-nsis:
  image: schnouki/pyinstaller-windows-ci:python3
  type: deploy
  script:
  - export VERSION_NUMBER=`date +%y.%m.%d.%H%M`
  - apt-get update -qy
  - apt-get install -y nsis unzip openssh-client sshpass p7zip-full curl libespeak-dev xvfb espeak-data
  # - wget -c https://aka.ms/vs/15/release/vs_BuildTools.exe
  #- xvfb-run wineserver -w
  #- xvfb-run winetricks -q dotnet462
  #- xvfb-run wine vs_BuildTools.exe --quiet --wait --norestart --nocache --add Microsoft.VisualStudio.Workload.VCTools --add Microsoft.VisualStudio.Component.VC.140 --add Microsoft.VisualStudio.Component.WinXP
  #- xvfb-run winetricks -q vcrun2015
  #- winetricks -q vcrun2015
  - wine python -m pip install -U pip
  - wine pip3 install -U setuptools
  - wine pip3 install -r requirements.txt
  - wget https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.zip
  - unzip ffmpeg-release-essentials.zip
  - wget --no-check-certificate https://mpv.srsfckn.biz/mpv-dev-latest.7z
  - 7z x -ompv mpv-dev-latest.7z
  - wine pip uninstall -y enum34
  - wine PyInstaller subtitld_win.spec
  - makensis subtitld_win.nsi
  - export SSHPASS=$USER_PASS
  - sshpass -e scp -o stricthostkeychecking=no Subtitld*Installer.exe jonata@jonata.org:/home/jonata/subtitld.jonata.org/packages/
  - "curl -d '{ \"number\":\"'\"$VERSION_NUMBER\"'\", \"is_stable\":\"False\" }' -H \"Content-Type: application/json\" -X POST https://api2.jonata.org/subtitld/windows_version\n"
  artifacts:
    paths:
    - Subtitld*Installer.exe
    expire_in: 1 week
  only:
  - master

#
# windowsnative-nsis:
#   image: python:3.8.4
#   tags:
#   - windows
#   type: deploy
#   script:
#   - $VERSION_NUMBER=(get-date -format "YYYY.MM.dd.hhmm")
#   #- apt-get update -qy
#   #- apt-get install -y nsis unzip openssh-client sshpass p7zip-full curl libespeak-dev xvfb
#   #- wget -c https://aka.ms/vs/15/release/vs_BuildTools.exe
#   #- xvfb-run wineserver -w
#   #- xvfb-run winetricks -q dotnet462
#   #- xvfb-run wine vs_BuildTools.exe --quiet --wait --norestart --nocache --add Microsoft.VisualStudio.Workload.VCTools --add Microsoft.VisualStudio.Component.VC.140 --add Microsoft.VisualStudio.Component.WinXP
#   #- xvfb-run winetricks -q vcrun2015
#   #- winetricks -q vcrun2015
#   - python -m pip install -U pip
#   - pip3 install -r requirements.txt
#   - wget https://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-latest-win64-static.zip
#   - unzip ffmpeg-latest-win64-static.zip
#   - wget --no-check-certificate https://mpv.srsfckn.biz/mpv-dev-latest.7z
#   - 7z x -ompv mpv-dev-latest.7z
#   #- wine pip uninstall -y enum34
#   - PyInstaller subtitld_win.spec
#   - makensis subtitld_win.nsi
#   - export SSHPASS=$USER_PASS
#   - sshpass -e scp -o stricthostkeychecking=no Subtitld*Installer.exe jonata@jonata.org:/home/jonata/subtitld.jonata.org/packages/
#   - "curl -d '{ \"number\":\"'\"$VERSION_NUMBER\"'\", \"is_stable\":\"False\" }' -H \"Content-Type: application/json\" -X POST https://api2.jonata.org/subtitld/windows_version\n"
#   artifacts:
#     paths:
#     - Subtitld*Installer.exe
#     expire_in: 1 week
#   only:
#   - master
