
version: 22.11.0.1.{build}

# pull_requests:
#   do_not_increment_build_number: true

# branches:
#   only:
#   - master

# skip_non_tags: false

image: Visual Studio 2019

# shallow_clone: true

# clone_depth: 1

clone_folder: C:\projects\subtitld

environment:
  PYTHONUNBUFFERED: 1
  PYTHONHOME: C:\Python39-x64

# build: off
# init:
#   - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))


install:
  - choco install rsvg-convert
  - choco install nsis

build_script:
  - ps: $env:PATH=$env:PYTHONHOME;$env:PYTHONHOME\scripts;$env:PYTHONHOME\tools\scripts;$env:PATH
  - ps: $now = Get-Date -Format yy.MM.dd.HHmm
  - ps: Start-FileDownload 'https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.zip'
  - ps: Expand-Archive -Path ffmpeg-release-essentials.zip
  - ps: C:\Python39-x64\python.exe -m pip install -U pip
  - ps: C:\Python39-x64\python.exe -m pip install -r requirements.txt
  - ps: C:\Python39-x64\python.exe -m pip install -U pyinstaller glfw pywin32
  - ps: $svg_path ="[[UPDATE WITH YOUR PAT]]"
  - ps: $svg_files = Get-ChildItem -Path $svg_path -File -Recurse -Filter *.svg
  - ps: >-

      ForEach ($svg_file in $svg_files)

          {

            $processingFile = $svg_file.FullName -replace [regex]::Escape($svg_path), ""

            $targetPath = $svg_file.Directory -replace [regex]::Escape($svg_path), $rootTargetPath

            $result = New-Item -ItemType Directory -Force -Path $targetPath

            $targetFilePath = Join-Path $targetPath $svg_file

            $targetFilePath = $targetFilePath -replace ".svg", ".png"



            $result = & rsvg-convert $svg_file.FullName -o $targetFilePath 2>&1



          }
  - ps: (Get-Content subtitld\graphics\stylesheet.qss).replace('.svg','.png') | Set-Content subtitld\graphics\stylesheet.qss
  - ps: (Get-Content subtitld\resources.qrc).replace('.svg','.png') | Set-Content subtitld\resources.qrc
  - ps: C:\Python39-x64\Scripts\pyside6-rcc.exe' subtitld\resources.qrc -o subtitld\resources_rc.py
  - ps: C:\Python39-x64\Scripts\PyInstaller.exe' subtitld_win.spec

  - ps: makensis.exe subtitld_win.nsi

after_build:
  - Move-Item -Path "dist/Subtitld Portable.exe" -Destination "dist/Subtitld $now Portable.exe"


artifacts:
  - path: .exe
    name: builds

deploy:
- provider: Webhook
  url: https://app.signpath.io/API/v1/9b1ff5d7-28fa-4698-83a0-7995dcbb8c85/Integrations/AppVeyor?ProjectSlug=subtitld&SigningPolicySlug=test-signing
  authorization:
     secure: FR+ZMCcQFzYUOtoPMDPzbQPKcnX6JtueF2oGstSvxQwoDV4nSNwFs4VHms8d75FEX8IK1ZJi2KTSZMGwBqC4lw==

