name: subtitld
summary: Subtitld
description: |
 Subtitld is a software to create and edit subtitles. Visit http://subtitld.org/ for more information.
icon: subtitld/graphics/subtitld.png
confinement: strict
adopt-info: subtitld
base: core22

plugs:
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes:gtk-3-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes:icon-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes:sounds-themes
  gsettings: null


apps:
  subtitld:
    command: bin/desktop-launch $SNAP/bin/subtitld
    environment:
      LC_ALL: C.UTF-8
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/blas:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/lapack:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/samba:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/vdpau:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri
      QT_QPA_PLATFORMTHEME: gtk3
      # DISABLE_WAYLAND: 1
    plugs:
      - gsettings
      - home
      - network
      - network-bind
      - browser-support
      - unity7
      - x11
      - optical-drive
      - wayland
      - desktop
      - removable-media
      - mount-observe

parts:
  prepare:
      plugin: nil
      build-packages:
          - software-properties-common
      prime: [-*]
  desktop-qt6:
      source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
      source-subdir: qt
      plugin: make
      after: [prepare]
      make-parameters: ["FLAVOR=qt5"]
      build-packages:
        - build-essential
        - qtbase5-dev
        - dpkg-dev
      stage-packages:
        - libopengl0
        - libglx0
        - libgl1
        - libegl1
        - libxkbcommon0
        - libfontconfig1
        - qtwayland5
        - libqt5gui5
        - qt5-style-plugins
        - libmpv1
        - ffmpeg
        - libffms2-4

  subtitld:
    plugin: python
    source: .
    after: [prepare, desktop-qt6]
    build-packages:
      - python3-dev
      - python3-setuptools
      - python3-venv
    build-environment:
      - LTS: jammy
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$VERSION_NUMBER"
      snapcraftctl set-grade "stable"
