name: subtitld
version: "18.08.2"
version-script: date +%y.%m.%d.%H%M
summary: Subtitld
description: |
 Subtitld is a software to create and edit subtitles. Visit http://subtitld.jonata.org/ for more information.
icon: dist/subtitld/graphics/subtitld.png
confinement: strict
grade: stable
base: core18
adopt-info: subtitld
assumes:
- command-chain

apps:
  subtitld:
    adapter: full
    command: subtitld/subtitld
    command-chain:
      - bin/desktop-launch
    environment:
        DISABLE_WAYLAND: 1
        QT_QPA_PLATFORMTHEME: gtk3
    plugs:
      - gsettings
      - home
      - network
      - network-bind
      - pulseaudio
      - unity7
      - x11
      - optical-drive
      - wayland
      - desktop
      - opengl
      - removable-media

plugs:
  # gtk-common-themes support
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes:gtk-3-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes:icon-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes:sounds-themes

parts:
  subtitld:
    plugin: dump
    source: .
    organize:
      'dist' : .
    stage-packages:
      - libgettextpo0
      - libchromaprint-tools
      - python3-libdiscid
      - python3-mutagen
      - python3-pyqt5
      - gettext
      - qtwayland5
      # gtk-common-themes support
      - qt5-gtk-platformtheme
    after:
      - desktop-qt5

  # Part for supporting various desktop technologies
  # Refer: https://github.com/ubuntu/snapcraft-desktop-helpers/blob/master/snapcraft.yaml
  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-depth: 1
    source-subdir: qt

    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - try: [appmenu-qt5] # not available on core18
      - locales-all
      - xdg-user-dirs
      - fcitx-frontend-qt5

layout:
    /usr/share/locale:
        bind: $SNAP/share/locale
