name: subtitld
version: "20.07.2"
version-script: echo $VERSION_NUMBER # date +%y.%m.%d.%H%M
summary: Subtitld
description: |
 Subtitld is a software to create and edit subtitles. Visit http://subtitld.jonata.org/ for more information.
icon: dist/subtitld/graphics/subtitld.png
confinement: strict
grade: stable
base: core18

apps:
  subtitld:
    command: desktop-launch snapcraft-preload $SNAP/subtitld/subtitld
    environment:
        LC_ALL: C.UTF-8
        GSETTINGS_SCHEMA_DIR: $SNAP/usr/share/glib-2.0/schemas
    plugs:
      - audio-playback
      - gsettings
      - home
      - network
      - network-bind
      - pulseaudio
      - unity7
      - x11
      - optical-drive
      - wayland
      - desktop
      - opengl
      - removable-media
      - mount-observe

plugs:
  # gtk-common-themes support
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes:gtk-3-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes:icon-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes:sounds-themes
  # gnome-3-34-1804:
  #   interface: content
  #   target: $SNAP/gnome-platform
  #   default-provider: gnome-3-34-1804

parts:
  subtitld:
    plugin: dump
    source: .
    organize:
      'dist' : .
    stage-packages:
      - ffmpeg
      - espeak-data
      - gsettings-desktop-schemas
      - libgtk-3-common
      #- desktop-gnome-platform
      # - libmpv1
      # gtk-common-themes support
      #- qt5-gtk-platformtheme
    after:
      - desktop-qt5

  snapcraft-preload:
          source: https://github.com/sergiusens/snapcraft-preload.git
          plugin: cmake
          build-packages:
            - on amd64:
              - gcc-multilib
              - g++-multilib
