name: subtitld
version: "18.08.2"
version-script: date +%y.%m.%d.%H%M
summary: Subtitld
description: |
 Subtitld is a software to create and edit subtitles. Visit http://subtitld.jonata.org/ for more information.
icon: dist/subtitld/graphics/subtitld.png
confinement: strict
grade: stable
base: core18

apps:
  subtitld:
    command: bin/desktop-launch $SNAP/subtitld/subtitld
    environment:
        DISABLE_WAYLAND: 1
        QT_QPA_PLATFORMTHEME: gtk3
    plugs:
      - gsettings
      - home
      - network
      - network-bind
      - pulseaudio
      - unity7
      - x11
      - optical-drive
      - wayland
      - desktop
      - opengl
      - removable-media

plugs:
  # gtk-common-themes support
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes:gtk-3-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes:icon-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes:sounds-themes

parts:
  subtitld:
    plugin: dump
    source: .
    organize:
      'dist' : .
    stage-packages:
      - ffmpeg
      #- libmpv1
      # gtk-common-themes support
      #- qt5-gtk-platformtheme
    after:
      - desktop-qt5
