name: subtitld
version: "18.08.2"
version-script: date +%y.%m.%d.%H%M
summary: Subtitld
description: |
 Subtitld is a software to create and edit subtitles. Visit http://subtitld.jonata.org/ for more information.
icon: graphics/subtitld.png
confinement: strict
grade: stable
#base: core16

apps:
  subtitld:
    environment:
      LC_ALL: C.UTF-8
      QT_DEBUG_PLUGINS: 1
    command: desktop-launch $SNAP/subtitld/subtitld
    plugs:
      - unity7
      - home
      - network
      - network-bind
      - desktop
      - desktop-legacy
      - mount-observe
      - removable-media
      - gsettings

plugs:
  gtk-3-themes:
    interface: content
    target: $SNAP/usr/share/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/usr/share/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/usr/share/sounds
    default-provider: gtk-common-themes

parts:
  subtitld:
    plugin: dump
    source: .
    organize:
      'dist' : .
    stage-packages:
      - ffmpeg
      - libmpv1
      - libqt5x11extras5
    after:
      - desktop-qt5
