name: subtitld
version: "18.08.2"
version-script: date +%y.%m.%d.%H%M
summary: Subtitld
description: |
 Subtitld is a software to create and edit subtitles. Visit http://subtitld.jonata.org/ for more information.
icon: dist/subtitld/graphics/subtitld.png
confinement: strict
grade: stable
#base: core16

apps:
  subtitld:
    environment:
      LC_ALL: C.UTF-8
      #XDG_DATA_DIRS: /usr/share/ubuntu:/usr/share/gnome:/usr/local/share/:/usr/share/
      #HOME: $(getent passwd $UID | cut -d ':' -f 6)
      #QT_IM_MODULE: cedilla
      #QT_STYLE_OVERRIDE: "gtk"
      #GS_LIB: $SNAP/usr/share/ghostscript/9.26/lib
      #DISABLE_WAYLAND: 1
    command: desktop-launch $SNAP/subtitld/subtitld
    plugs:
      - browser-support
      - unity7
      - home
      - network
      - desktop
      - desktop-legacy
      - mount-observe
      - removable-media
      - gsettings
      #- x11
      #- wayland

plugs:
  gtk-3-themes:
    interface: content
    target: $SNAP/usr/share/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/usr/share/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/usr/share/sounds
    default-provider: gtk-common-themes

parts:
  subtitld:
    plugin: dump
    source: .
    organize:
      'dist' : .
      #'subtitld/PySide2/plugins/platformthemes/libqgtk3.so' : '/usr/lib/x86_64-linux-gnu/qt5/plugins/platformthemes/libqgtk3.so'
    stage-packages:
      - ffmpeg
      - libmpv1
      #- unity-gtk3-module
      #- language-selector-common
      #-ghostscript
      #- libreoffice-writer
      #- unoconv
      #- qt5-gtk-platformtheme
      #- libc6
      #- qtwayland5
      #- python3-pip
    #override-build: |
    #    apt-get update -qy
    #    apt-get -y install python3-pip python3-dev
    #    python3 -m pip install PySide2 setuptools
    #    python3 -m pip install google-api-python-client oauth2client requests pyinstaller beautifulsoup4 unoconv
    #    python3 -m PyInstaller subtitld_linux.spec
    #    mv dist/subtitld ${SNAPCRAFT_PART_INSTALL}/usr/share/subtitld
    after:
      - desktop-qt5
